[tool.poetry]
name = "confuk"
version = "0.2.0"
description = "Very opinionated configuration loading package for Python projects"
authors = ["Krzysztof J. Czarnecki <kjczarne@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
toml = "^0.10.2"
pydantic = "^2.5.3"
easydict = "^1.11"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.4"
pylint = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
